#!/bin/bash

sed_args=(
  # remove first and last few lines
  -e 's/Found [0-9].*//')
  -e 's/-->.*//')
  -e 's/^ *\[.*//')

  # replace certain characters
  -e 's/``/\"/')
  -e "s/''/\"/")
  -e 's/--/- /')

  # remove blank lines
  -e 's/ *$//g')
  -e '/^$/d')
  -e '/^ *$/d')

  # fix indentation
  -e 's/^      ([^ ])/         \1/')
  -e 's/^(                                                  )([^ ])/\1  \2/')
  -e 's/^   ([^ ])/      \1/')
  -e '1s/^/  /')
  -e 's/^([^ ])/      \1/')
)
text=$(sdcv "$1" | sed -E "${sed_args[@]}")

# fit to terminal width
width=$(tput cols)
hline=$(
  printf '=%.0s' $(seq 1 $width)
  echo
)

output="$(
  echo $hline
  padding=$((($width + ${#1}) / 2))
  printf "%*s\n" $padding "${1^}"
  echo $hline
  echo "$text"
)"

echo "$output" | less -FX
